version: "3.9"
services:

  database:
    image: "postgres:14.2-alpine3.15"
    ports:
      - "5432:5432"
    volumes:
      - "~/dashboard-backend/postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=dashboard"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"

  qodana:
    image: "jetbrains/qodana-jvm-community:2022.1"
    ports:
      - "8081:8080"
    volumes:
      - ".:/data/project/"
      - "./qodana:/data/results"
    command:
      - "--show-report"