### first
POST http://localhost:8080/task
Content-Type: application/json

{
  "name": "First task"
}

###
POST http://localhost:8080/task/update
Content-Type: application/json

{
  "id": "b7735216-71c4-48a1-acfb-0a1dc62b58a7",
  "name": "First task",
  "description": "Something new new",
  "completed": false
}

###
GET http://localhost:8080/task
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjUyNzM4OTExLCJleHAiOjE2NTI3MzkwOTF9.7y3XP03WE1gNVhUe63_g56moyuRw0LSsH4E1zInlSek

###
DELETE http://localhost:8080/task/dc6195dc-ea91-480e-be7d-6a7e4fd6240e

###
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "username": "test",
  "email": "test@gmail.com",
  "password": "password123"
}

### Login
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "test",
  "password": "password123"
}