### add task
POST http://localhost:8080/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjUzNzM5MTA0LCJleHAiOjE2NTM3MzkyODR9.gb9Bw7-kDU_-zIT4a6rRdCMjEJX16KIXwRCrWuRe5ag

{
  "name": "Something new"
}

### complete task
POST http://localhost:8080/task/complete/1e00eae2-9649-42cf-909e-cd78b191de56
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjUzNzM5MTA0LCJleHAiOjE2NTM3MzkyODR9.gb9Bw7-kDU_-zIT4a6rRdCMjEJX16KIXwRCrWuRe5ag

### update task
POST http://localhost:8080/task/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjUzNzM5MTA0LCJleHAiOjE2NTM3MzkyODR9.gb9Bw7-kDU_-zIT4a6rRdCMjEJX16KIXwRCrWuRe5ag

{
  "id": "1e00eae2-9649-42cf-909e-cd78b191de56",
  "name": "Something new changed",
  "description": "Something new new",
  "completed": true
}

### get all tasks
GET http://localhost:8080/task
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjUzNzM5MTA0LCJleHAiOjE2NTM3MzkyODR9.gb9Bw7-kDU_-zIT4a6rRdCMjEJX16KIXwRCrWuRe5ag

### delete task
DELETE http://localhost:8080/task/dc6195dc-ea91-480e-be7d-6a7e4fd6240e

### register user
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password"
}

### login
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password"
}

### refreshToken
GET http://localhost:8080/refreshToken
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjUyOTEzMzk3LCJleHAiOjE2NTQxMjI5OTd9.wtoMFpZS-_oaf495dIyuRv3UuY7k_RK_zI81Au5DPGY