### login
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password"
}

> {%
    // saves in a global object, this is not stored in files, just in memory I guess.
    client.global.set("auth_token", response.body.accessToken)
    client.global.set("refresh_token", response.body.refreshToken)
%}

### refreshToken
GET http://localhost:8080/refreshToken
Authorization: Bearer {{ refresh_token }}

> {%
    // saves in a global object, this is not stored in files, just in memory I guess.
    client.global.set("auth_token", response.body.accessToken)
%}