### add task
POST http://localhost:8080/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY1ODYwNTQ3NCwiZXhwIjoxNjU4NjA1NjU0fQ.Q3gJb-z-Gc2qIGWlngNXUsXVQOLyqIeRbJhHS2GBTGk

{
  "name": "Something new 2"
}

### complete task
POST http://localhost:8080/task/complete/c8b4497e-a481-458c-9b32-ba51161c8f9d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY1ODYwNTQ3NCwiZXhwIjoxNjU4NjA1NjU0fQ.Q3gJb-z-Gc2qIGWlngNXUsXVQOLyqIeRbJhHS2GBTGk

### update task
POST http://localhost:8080/task/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY1ODUyNzM4MSwiZXhwIjoxNjU4NTI3NTYxfQ.eMngu2n67vQ9esKc7IyNRtaNm2X6HYXHYo9Nqi5xOOE

{
  "id": "02e13fb7-10db-411a-8e59-a022de5d11cd",
  "name": "Something newerasdf",
  "description": "My new description",
  "completed": false
}

### get all tasks
GET http://localhost:8080/task
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY1ODc4OTU3NywiZXhwIjoxNjU4Nzg5NzU3fQ.JtFjt6_C_UTxSP7S_vw1A720T49GkbzGnVarRMFy9B0

### delete task
DELETE http://localhost:8080/task/c8b4497e-a481-458c-9b32-ba51161c8f9d
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTY1ODUyNzM4MSwiZXhwIjoxNjU4NTI3NTYxfQ.eMngu2n67vQ9esKc7IyNRtaNm2X6HYXHYo9Nqi5xOOE

### register user
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password"
}

### login
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password"
}

### refreshToken
GET http://localhost:8080/refreshToken
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjUyOTEzMzk3LCJleHAiOjE2NTQxMjI5OTd9.wtoMFpZS-_oaf495dIyuRv3UuY7k_RK_zI81Au5DPGY