### add weight
POST localhost:8080/weight
Content-Type: application/json
Authorization: Bearer {{ auth_token }}

{
  "value": 75.2
}

### get weight
GET localhost:8080/weight
Authorization: Bearer {{ auth_token }}

### delete weight
DELETE localhost:8080/weight/{{ weight_to_delete_id }}
Authorization: Bearer {{ auth_token }}

### update weight
PATCH localhost:8080/weight
Content-Type: application/json
Authorization: Bearer {{ auth_token }}

{
  "id": 538335745972301266,
  "value": 75.5,
  "date": "2024-01-25T12:34:03.631839Z",
  "unit": "KG"
}