### add weight
POST localhost:8080/weight
Content-Type: application/json
Authorization: Bearer {{ auth_token }}

{
  "value": 75.2
}

### get weight
GET localhost:8080/weight
Authorization: Bearer {{ auth_token }}

### delete weight
DELETE localhost:8080/weight/{{ weight_to_delete_id }}
Authorization: Bearer {{ auth_token }}
